
version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
       - ./:/usr/src/app/challenge3
       - /usr/src/app/challenge3/node_modules
    ports:
      - "3000:3000"
    command: command: ["npm", "run", "dev"]
